[package]
edition = "2024"
name = "lox-interpreter"
version = "0.1.1"

[dependencies]
codespan-reporting = "0.12.0"
lalrpop-util = "0.22.1"
logos = "0.15.0"
termcolor = "1.4.1"
thiserror = "2.0.12"

[build-dependencies]
lalrpop = "0.22.1" 
