[package]
edition = "2024"
name = "lox"
version = "0.1.1"

[dependencies]
codespan-reporting = "0.12.0"
lalrpop-util = "0.22.2"
logos = "0.15.0"
rand = "0.9.1"
termcolor = "1.4.1"
thiserror = "2.0.12"

[build-dependencies]
lalrpop = "0.22.2" 
